=== mozilla-rally/mozilla-pipeline-schemas/schemas/messaging-system/onboarding/onboarding.1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "mozPipelineMetadata": {
    "bq_dataset_family": "messaging_system",
    "bq_metadata_format": "structured",
    "bq_table": "onboarding_v1",
    "expiration_policy": {
      "delete_after_days": 180
    }
  },
  "properties": {
    "addon_version": {
      "type": "string"
    },
    "attribution": {
      "properties": {
        "campaign": {
          "description": "Identifier of the particular campaign that led to the download of the product.",
          "type": "string"
        },
        "content": {
          "description": "Identifier to indicate the particular link within a campaign.",
          "type": "string"
        },
        "dltoken": {
          "description": "Unique token created at Firefox download time, see bug 1757451",
          "type": "string"
        },
        "experiment": {
          "description": "Funnel experiment parameters, see bug 1567339",
          "type": "string"
        },
        "medium": {
          "description": "Category of the source, such as 'organic' for a search engine.",
          "type": "string"
        },
        "source": {
          "description": "Referring partner domain, when install happens via a known partner.",
          "type": "string"
        },
        "ua": {
          "description": "Derived user agent, see bug 1595063",
          "type": "string"
        },
        "variation": {
          "description": "Funnel experiment parameters, see bug 1567339",
          "type": "string"
        }
      },
      "type": "object"
    },
    "browser_session_id": {
      "description": "A mirror of the browser sessionId, as defined in https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/main/schemas/telemetry/main/main.4.schema.json",
      "type": "string"
    },
    "client_id": {
      "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
      "type": "string"
    },
    "event": {
      "description": "An event identifier",
      "type": "string"
    },
    "event_context": {
      "description": "A string that describes the context about this event",
      "type": "string"
    },
    "experiments": {
      "additionalProperties": {
        "properties": {
          "branch": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "description": "An object to record all active experiments, experiments IDs are stored as keys, and the value object stores the branch information. Example: {\"experiment_1\": {\"branch\": \"control\"}, \"experiment_2\": {\"branch\": \"treatment\"}}. This deprecates the \"shield_id\" used in activity-stream and messaging-system.",
      "type": "object"
    },
    "locale": {
      "type": "string"
    },
    "message_id": {
      "type": "string"
    },
    "profile_creation_date": {
      "type": "integer"
    },
    "release_channel": {
      "type": "string"
    },
    "shield_id": {
      "description": "[DEPRECATED]: use `experiments` instead. A semicolon separated string to store a list of Shield study IDs",
      "type": "string"
    },
    "version": {
      "type": "string"
    }
  },
  "required": [
    "client_id",
    "event",
    "message_id",
    "addon_version",
    "version",
    "locale"
  ],
  "title": "onboarding",
  "type": "object"
}

=== mozilla-rally/mozilla-pipeline-schemas/validation/messaging-system/onboarding.1.attribution.pass.json
{
  "client_id": "94642acb-4996-034b-916c-147da723cc41",
  "event": "IMPRESSION",
  "event_context": "n/a",
  "message_id": "12345",
  "locale": "en-US",
  "version": "71.0a1",
  "release_channel": "nightly",
  "addon_version": "20181206092619",
  "profile_creation_date": 17817,
  "attribution": {
    "source": "google.com",
    "medium": "referral",
    "campaign": "Firefox-Brand-US-Chrome",
    "content": "(not set)",
    "experiment": "(not set)",
    "variation": "(not set)",
    "ua": "chrome",
    "dltoken": "(not set)"
  }
}
