=== mozilla-rally/mozilla-pipeline-schemas/schemas/pioneer-citp-news-disinfo-two/rallymeasurements/rallymeasurements.2.schema.json
{
  "$comment": "Information about this study is available at https://github.com/citp/news-disinformation-study",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "mozPipelineMetadata": {
    "bq_dataset_family": "pioneer_citp_news_disinfo_two",
    "bq_metadata_format": "pioneer",
    "bq_table": "rallymeasurements_v2",
    "expiration_policy": {
      "delete_after_days": 180
    }
  },
  "properties": {
    "newsAndDisinfo.linkExposure": {
      "additionalProperties": false,
      "properties": {
        "trackedExposuresByCategory": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "categoryExposuresCount": {
                "type": "integer"
              },
              "dayOfWeek": {
                "type": "integer"
              },
              "exposureDestinationTrimmedUrl": {
                "type": "string"
              },
              "exposureSourceTrimmedUrl": {
                "type": "string"
              },
              "timeOfDay": {
                "type": "integer"
              }
            },
            "type": "object"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "newsAndDisinfo.methodology": {
      "additionalProperties": false,
      "properties": {
        "methodologyVisits": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "attentionDwellTime": {
                "type": "number"
              },
              "attentionDwellTimePlus": {
                "type": "number"
              },
              "attentionTimeToNextLoad": {
                "type": "number"
              },
              "attentionWebScience": {
                "type": "number"
              },
              "dayOfMonthStart": {
                "type": "number"
              },
              "isHistoryChange": {
                "type": "boolean"
              },
              "monthOfYearStart": {
                "type": "number"
              },
              "parentHistory": {
                "type": "string"
              },
              "parentLoadTime": {
                "type": "string"
              },
              "parentLoadTimeToHistory": {
                "type": "boolean"
              },
              "parentReferrer": {
                "type": "string"
              },
              "parentReferrerPathPresent": {
                "type": "boolean"
              },
              "parentReferrerToHistory": {
                "type": "boolean"
              },
              "parentReferrerToLoadTime": {
                "type": "boolean"
              },
              "parentWebScience": {
                "type": "string"
              },
              "parentWebSciencePathPresent": {
                "type": "boolean"
              },
              "parentWebScienceToHistory": {
                "type": "boolean"
              },
              "parentWebScienceToLoadTime": {
                "type": "boolean"
              },
              "parentWebScienceToReferrer": {
                "type": "boolean"
              },
              "prevTTNL": {
                "type": "number"
              },
              "timeOfDayStart": {
                "type": "number"
              },
              "visitTrimmedUrl": {
                "type": "string"
              },
              "yearStart": {
                "type": "number"
              }
            },
            "type": "object"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "newsAndDisinfo.pageNavigation": {
      "additionalProperties": false,
      "properties": {
        "trackedVisitsByCategory": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "categoryAttention": {
                "type": "number"
              },
              "categoryScroll": {
                "type": "number"
              },
              "categoryVisitsCount": {
                "type": "integer"
              },
              "classifierResults": {
                "additionalProperties": {
                  "type": "integer"
                },
                "description": "additional properties are the name of the classifier, with the classification result as the value",
                "type": "object"
              },
              "dayOfWeek": {
                "type": "integer"
              },
              "sourceTrimmedUrlFromReferrer": {
                "type": "string"
              },
              "sourceTrimmedUrlFromTransitions": {
                "type": "string"
              },
              "timeOfDay": {
                "type": "integer"
              },
              "visitTrimmedUrl": {
                "type": "string"
              }
            },
            "type": "object"
          },
          "type": "array"
        },
        "untrackedAttention": {
          "type": "number"
        },
        "untrackedVisitsCount": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "newsAndDisinfo.socialMediaLinkSharing": {
      "additionalProperties": false,
      "properties": {
        "linkSharesByPlatform": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "platform": {
                "enum": [
                  "facebook",
                  "twitter",
                  "reddit"
                ],
                "type": "string"
              },
              "trackedSharesByCategory": {
                "items": {
                  "additionalProperties": false,
                  "properties": {
                    "categorySharesCount": {
                      "type": "integer"
                    },
                    "categoryVisitAttention": {
                      "type": "number"
                    },
                    "categoryVisitsInHistoryCount": {
                      "type": "integer"
                    },
                    "categoryVisitsInPageNavigationCount": {
                      "type": "integer"
                    },
                    "classifierResults": {
                      "additionalProperties": {
                        "type": "integer"
                      },
                      "description": "additional properties are the name of the classifier, with the classification result as the value",
                      "type": "object"
                    },
                    "dayOfWeek": {
                      "type": "integer"
                    },
                    "facebookReshareSource": {
                      "type": "string"
                    },
                    "shareAudience": {
                      "enum": [
                        "public",
                        "restricted",
                        "unknown"
                      ],
                      "type": "string"
                    },
                    "sharedTrimmedUrl": {
                      "type": "string"
                    },
                    "timeOfDay": {
                      "type": "integer"
                    },
                    "visitSourceFromTransitions": {
                      "type": "string"
                    }
                  },
                  "type": "object"
                },
                "type": "array"
              },
              "untrackedSharesCount": {
                "type": "integer"
              }
            },
            "type": "object"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "newsAndDisinfo.surveyId": {
      "description": "ID sent to Qualtrics, for associating survey responses with telemetry data",
      "type": "string"
    },
    "newsAndDisinfo.version": {
      "type": "string"
    }
  },
  "type": "object"
}

=== mozilla-rally/mozilla-pipeline-schemas/validation/pioneer-citp-news-disinfo-two/rallymeasurements.2.missingmethodology.pass.json
{
  "newsAndDisinfo.pageNavigation": {
    "trackedVisitsByCategory": [
      {
        "visitTrimmedUrl": "www.washingtonpost.com",
        "sourceTrimmedUrlFromReferrer": "t.co",
        "sourceTrimmedUrlFromTransitions": "t.co",
        "dayOfWeek": 5,
        "timeOfDay": 20,
        "classifierResults": {
          "covid-page-classifier": 2,
          "pol-page-classifier": 2
        },
        "categoryVisitsCount": 2,
        "categoryAttention": 17750,
        "categoryScroll": 0.3523031465968598
      },
      {
        "visitTrimmedUrl": "www.bbc.com",
        "sourceTrimmedUrlFromReferrer": "www.washingtonpost.com",
        "sourceTrimmedUrlFromTransitions": "www.washingtonpost.com",
        "dayOfWeek": 5,
        "timeOfDay": 20,
        "classifierResults": {
          "covid-page-classifier": 2,
          "pol-page-classifier": 2
        },
        "categoryVisitsCount": 1,
        "categoryAttention": 55917,
        "categoryScroll": 0.5355242566510172
      }
    ],
    "untrackedVisitsCount": 20,
    "untrackedAttention": 141007
  },
  "newsAndDisinfo.socialMediaLinkSharing": {
    "linkSharesByPlatform": [
      {
        "platform": "facebook",
        "trackedSharesByCategory": [],
        "untrackedSharesCount": 0
      },
      {
        "platform": "twitter",
        "trackedSharesByCategory": [
          {
            "sharedTrimmedUrl": "www.washingtonpost.com",
            "visitSourceFromTransitions": "",
            "classifierResults": {},
            "shareAudience": "restricted",
            "dayOfWeek": 5,
            "timeOfDay": 20,
            "categorySharesCount": 2,
            "categoryVisitsInPageNavigationCount": 0,
            "categoryVisitAttention": 0,
            "categoryVisitsInHistoryCount": 0
          },
          {
            "sharedTrimmedUrl": "www.wsj.com",
            "visitSourceFromTransitions": "t.co",
            "classifierResults": {
              "covid-page-classifier": 2,
              "pol-page-classifier": 1
            },
            "shareAudience": "restricted",
            "dayOfWeek": 5,
            "timeOfDay": 20,
            "categorySharesCount": 1,
            "categoryVisitsInPageNavigationCount": 1,
            "categoryVisitAttention": 19436,
            "categoryVisitsInHistoryCount": 1
          }
        ],
        "untrackedSharesCount": 1
      },
      {
        "platform": "reddit",
        "trackedSharesByCategory": [],
        "untrackedSharesCount": 0
      }
    ]
  },
  "newsAndDisinfo.linkExposure": {
    "trackedExposuresByCategory": [
      {
        "exposureSourceTrimmedUrl": "www.google.com",
        "exposureDestinationTrimmedUrl": "www.npr.org",
        "dayOfWeek": 5,
        "timeOfDay": 20,
        "categoryExposuresCount": 6
      },
      {
        "exposureSourceTrimmedUrl": "www.google.com",
        "exposureDestinationTrimmedUrl": "other",
        "dayOfWeek": 5,
        "timeOfDay": 20,
        "categoryExposuresCount": 7
      },
      {
        "exposureSourceTrimmedUrl": "twitter.com",
        "exposureDestinationTrimmedUrl": "www.npr.org",
        "dayOfWeek": 5,
        "timeOfDay": 20,
        "categoryExposuresCount": 2
      }
    ]
  },
  "newsAndDisinfo.surveyId": "178b7466-8f09-48ad-b22a-9a02ef3e9b5b",
  "newsAndDisinfo.version": "2.0"
}
